doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
                gedmo_tree:
                    type: annotation
                    prefix: Gedmo\Tree\Document
                    dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Document"
                    alias: GedmoTree # (optional) it will default to the name set for the mapping
                    is_bundle: false