fm_elfinder:
    assets_path: /assets # chemin des fichiers JS
    instances:
        default:
            locale: fr # Langue
            editor: ckeditor # Editeur utilisé
            fullscreen: true # Taille d'affichage
            theme: smoothness # Thème à utiliser
            # include_assets: true # Charge automatiquement les fichiers nécessaires
            connector:
                debug: false # Désactive le débug
                roots:
                    images:
                        show_hidden: false # Masque les fichiers cachés
                        driver: LocalFileSystem # Pilote des fichiers
                        path: image # Chemin d'upload
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all'] # Fichiers interdits
                        upload_max_size: 500k # Taille maximum
                    docs:
                        show_hidden: false # Masque les fichiers cachés
                        driver: LocalFileSystem # Pilote des fichiers
                        path: docs # Chemin d'upload
                        upload_allow: ['application/pdf']
                        upload_deny: ['all'] # Fichiers interdits
                        upload_max_size: 10M # Taille maximum
        form:
            locale: fr # defaults to current request locale
            editor: custom # other choices are tinymce or simple, and form
            editor_template: _elFinder/_widget.html.twig
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            # include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: image
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M