# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    auto_inline: false
    configs:
        main_config:
            language: fr
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', 'Unlink', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', 'Iframe', '-', 'TextColor', 'BGColor'] }
                - { name: "commands", items: ['Styles', 'Format','FontSize', '-', 'Source'] }
            contentsCss: ['build/app.css']
            disallowedContent: 'h1'
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            stylesSet: "custom_content"
            coreStyles_bold: { element: 'b' }
            coreStyles_italic: { element: 'i' }
    styles:
        custom_content:
            - { name: "Titre H2", element: "h2"}
            - { name: "Titre H3", element: "h3"}
            - { name: "Titre H4", element: "h4"}
            - { name: "Paragraphe", element: "p"}
            - { name: "Séparateur", element: "hr"}
            - { name: "Texte en vert", element: "span", attributes: { 'class': 'green' }}
            - { name: "Texte en jaune", element: "span", attributes: { 'class': 'yellow' }}