# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        name: SFSESSID # The name is changed in order to avoid session conflict on sub/super domain

    #esi: true
    #fragments: true
    php_errors:
        log: true

    error_controller: App\Controller\ErrorController::show
