<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentZoneHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['path']) || (! empty($this->class->fieldMappings['path']['nullable']) && array_key_exists('path', $data))) {
            $value = $data['path'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['path']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['path']->setValue($document, $return);
            $hydratedData['path'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['parent'])) {
            $reference = $data['parent'];

            if ($this->class->fieldMappings['parent']['storeAs'] !== ClassMetadata::REFERENCE_STORE_AS_ID && ! is_array($reference)) {
                throw HydratorException::associationTypeMismatch('App\Document\Zone', 'parent', 'array', gettype($reference));
            }

            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['parent'], $reference);
            $identifier = ClassMetadata::getReferenceId($reference, $this->class->fieldMappings['parent']['storeAs']);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($identifier);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['parent']->setValue($document, $return);
            $hydratedData['parent'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['level']) || (! empty($this->class->fieldMappings['level']['nullable']) && array_key_exists('level', $data))) {
            $value = $data['level'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['level']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['level']->setValue($document, $return);
            $hydratedData['level'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nom']) || (! empty($this->class->fieldMappings['nom']['nullable']) && array_key_exists('nom', $data))) {
            $value = $data['nom'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['nom']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['nom']->setValue($document, $return);
            $hydratedData['nom'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['code']) || (! empty($this->class->fieldMappings['code']['nullable']) && array_key_exists('code', $data))) {
            $value = $data['code'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['code']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['code']->setValue($document, $return);
            $hydratedData['code'] = $return;
        }
        return $hydratedData;
    }
}