<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxoZFc5\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxoZFc5/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNxoZFc5.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNxoZFc5\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerNxoZFc5\App_KernelProdContainer([
    'container.build_hash' => 'NxoZFc5',
    'container.build_id' => '51cab68c',
    'container.build_time' => 1647438643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxoZFc5');
