version: '2'
services:
  nginx:
    image: evild/alpine-nginx:1.9.15-openssl
    container_name: nginx-harmonie
    links:
      - php
    volumes:
      - ../:/var/www/html/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    tmpfs:
      - /var/log/nginx
      - /tmp
    ports:
      - 8080:80
    #   - 8443:443
  php:
    build: php-mongodb
    container_name: php-harmonie
    volumes:
      - ../:/var/www/html
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb-harmonie
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
