<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9_H8oxtService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9.h8oxt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9.h8oxt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dataTableFactory' => ['services', 'Omines\\DataTablesBundle\\DataTableFactory', 'getDataTableFactoryService', true],
            'documentManager' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService', true],
        ], [
            'dataTableFactory' => 'Omines\\DataTablesBundle\\DataTableFactory',
            'documentManager' => '?',
        ]);
    }
}
