<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DbKBlvjService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.dbKBlvj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dbKBlvj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'App\\Service\\PageCacheManager', 'getPageCacheManagerService', true],
        ], [
            'cache' => 'App\\Service\\PageCacheManager',
        ]);
    }
}
