<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U9sPiibService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.u9sPiib' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u9sPiib'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'rdvfConnector' => ['privates', 'App\\Service\\RdvfConnector', 'getRdvfConnectorService', true],
            'reCaptchaChecker' => ['privates', 'App\\Service\\ReCaptchaChecker', 'getReCaptchaCheckerService', true],
        ], [
            'mailer' => '?',
            'rdvfConnector' => 'App\\Service\\RdvfConnector',
            'reCaptchaChecker' => 'App\\Service\\ReCaptchaChecker',
        ]);
    }
}
