<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_Wco6SLO_ThrowableService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Wco6SLO.Throwable' shared service.
     *
     * @return \Throwable
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Wco6SLO": it references interface "Throwable" but no such service exists. Did you create a class that implements this interface?');
    }
}
