<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L5YUv17Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.l5YUv17' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l5YUv17'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'linkChecker' => ['privates', 'App\\Service\\LinkChecker', 'getLinkCheckerService', true],
        ], [
            'linkChecker' => 'App\\Service\\LinkChecker',
        ]);
    }
}
