<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvExporterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Omines\DataTablesBundle\Exporter\Csv\CsvExporter' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\Exporter\Csv\CsvExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Omines\\DataTablesBundle\\Exporter\\Csv\\CsvExporter'] = new \Omines\DataTablesBundle\Exporter\Csv\CsvExporter();
    }
}
