<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateLocaleFilterRuntimeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Twig\DateLocaleFilterRuntime' shared autowired service.
     *
     * @return \App\Twig\DateLocaleFilterRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Twig\\DateLocaleFilterRuntime'] = new \App\Twig\DateLocaleFilterRuntime();
    }
}
