<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugLoggerInterfaceService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Wco6SLO.Symfony\Component\HttpKernel\Log\DebugLoggerInterface' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Log\DebugLoggerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Wco6SLO": it references interface "Symfony\\Component\\HttpKernel\\Log\\DebugLoggerInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "monolog.logger", "monolog.logger.request", "monolog.logger.console", "monolog.logger.cache", "monolog.logger.http_client", "monolog.logger.translation", "monolog.logger.php", "monolog.logger.router", "monolog.logger.security", "monolog.logger.doctrine".');
    }
}
