<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelExporterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Omines\DataTablesBundle\Exporter\Excel\ExcelExporter' shared autowired service.
     *
     * @return \Omines\DataTablesBundle\Exporter\Excel\ExcelExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Omines\\DataTablesBundle\\Exporter\\Excel\\ExcelExporter'] = new \Omines\DataTablesBundle\Exporter\Excel\ExcelExporter();
    }
}
