<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfoDoctrineODMCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Doctrine\Bundle\MongoDBBundle\Command\InfoDoctrineODMCommand' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\InfoDoctrineODMCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Doctrine\\Bundle\\MongoDBBundle\\Command\\InfoDoctrineODMCommand'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\InfoDoctrineODMCommand(($container->services['doctrine_mongodb'] ?? $container->load('getDoctrineMongodbService')));

        $instance->setName('doctrine:mongodb:mapping:info');

        return $instance;
    }
}
