<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkCheckerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\LinkChecker' shared autowired service.
     *
     * @return \App\Service\LinkChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\LinkChecker'] = new \App\Service\LinkChecker(($container->services['doctrine_mongodb.odm.default_document_manager'] ?? $container->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
