<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getORMAdapterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter' autowired service.
     *
     * @return \Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter'] = function () use ($container) {
            return new \Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter(NULL);
        };

        return $container->factories['service_container']['Omines\\DataTablesBundle\\Adapter\\Doctrine\\ORMAdapter']();
    }
}
