<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageCacheManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\PageCacheManager' shared autowired service.
     *
     * @return \App\Service\PageCacheManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['slugger'] ?? ($container->privates['slugger'] = new \Symfony\Component\String\Slugger\AsciiSlugger('fr')));
        $b = ($container->services['twig'] ?? $container->load('getTwigService'));

        return $container->privates['App\\Service\\PageCacheManager'] = new \App\Service\PageCacheManager($container, ($container->services['doctrine_mongodb.odm.default_document_manager'] ?? $container->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService')), new \App\Service\ShortcodeRenderer($a, $b, ($container->services['form.factory'] ?? $container->load('getForm_FactoryService'))), new \App\Service\ContentParser($a), $b, ($container->services['cache.app'] ?? $container->load('getCache_AppService')), ($container->privates['App\\Service\\VideoCacheManager'] ?? $container->load('getVideoCacheManagerService')));
    }
}
