<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReCaptchaCheckerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ReCaptchaChecker' shared autowired service.
     *
     * @return \App\Service\ReCaptchaChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ReCaptchaChecker'] = new \App\Service\ReCaptchaChecker();
    }
}
