<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveUserCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\RemoveUserCommand' shared autowired service.
     *
     * @return \App\Command\RemoveUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\RemoveUserCommand'] = $instance = new \App\Command\RemoveUserCommand(($container->privates['App\\Service\\UserManager'] ?? $container->load('getUserManagerService')));

        $instance->setName('app:remove-user');

        return $instance;
    }
}
