<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaticPromiseTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Custom\StaticPromiseType' shared autowired service.
     *
     * @return \App\Form\Custom\StaticPromiseType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Custom\\StaticPromiseType'] = new \App\Form\Custom\StaticPromiseType();
    }
}
