<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwigColumnService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Omines\DataTablesBundle\Column\TwigColumn' autowired service.
     *
     * @return \Omines\DataTablesBundle\Column\TwigColumn
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['Omines\\DataTablesBundle\\Column\\TwigColumn'] = function () use ($container) {
            return new \Omines\DataTablesBundle\Column\TwigColumn(($container->services['twig'] ?? $container->load('getTwigService')));
        };

        return $container->factories['service_container']['Omines\\DataTablesBundle\\Column\\TwigColumn']();
    }
}
