<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTailCursorDoctrineODMCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Doctrine\Bundle\MongoDBBundle\Command\TailCursorDoctrineODMCommand' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\TailCursorDoctrineODMCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Doctrine\\Bundle\\MongoDBBundle\\Command\\TailCursorDoctrineODMCommand'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\TailCursorDoctrineODMCommand();

        $instance->setName('doctrine:mongodb:tail-cursor');

        return $instance;
    }
}
