<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateSchemaDoctrineODMCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Doctrine\Bundle\MongoDBBundle\Command\UpdateSchemaDoctrineODMCommand' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\UpdateSchemaDoctrineODMCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Doctrine\\Bundle\\MongoDBBundle\\Command\\UpdateSchemaDoctrineODMCommand'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\UpdateSchemaDoctrineODMCommand();

        $instance->setName('doctrine:mongodb:schema:update');

        return $instance;
    }
}
