<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\UserManager' shared autowired service.
     *
     * @return \App\Service\UserManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\UserManager'] = new \App\Service\UserManager(($container->services['doctrine_mongodb.odm.default_document_manager'] ?? $container->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService')), ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));
    }
}
