<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\UserAdminController' shared autowired service.
     *
     * @return \App\Controller\UserAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\UserAdminController'] = $instance = new \App\Controller\UserAdminController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\UserAdminController', $container));

        return $instance;
    }
}
