<?php

namespace ContainerNxoZFc5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZoneTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ZoneType' shared autowired service.
     *
     * @return \App\Form\ZoneType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ZoneType'] = new \App\Form\ZoneType();
    }
}
